# Generated by Django 4.2.7 on 2025-11-01 00:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                ("services", models.JSONField(default=list)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                (
                    "price_per_session",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("online", "Online"),
                            ("ambos", "Ambos"),
                        ],
                        default="presencial",
                        max_length=20,
                    ),
                ),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city"], name="professiona_city_05ae87_idx"),
                    models.Index(fields=["state"], name="professiona_state_26d882_idx"),
                    models.Index(
                        fields=["price_per_session"],
                        name="professiona_price_p_2559c8_idx",
                    ),
                    models.Index(
                        fields=["attendance_type"],
                        name="professiona_attenda_57b485_idx",
                    ),
                ],
            },
        ),
    ]
