# Generated by Django 4.2.7 on 2025-11-02 02:37

from django.db import migrations, models
import storage.backends


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storage.backends.ProfilePhotoStorage(),
                upload_to="photos/",
            ),
        ),
    ]
