# Generated by Django 4.2.7 on 2025-11-04 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import professionals.validators
import storage.backends


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("professionals", "0002_alter_professional_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="bio",
            field=models.TextField(validators=[professionals.validators.validate_bio]),
        ),
        migrations.AlterField(
            model_name="professional",
            name="name",
            field=models.CharField(
                max_length=255, validators=[professionals.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[professionals.validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=storage.backends.ProfilePhotoStorage(),
                upload_to="photos/",
                validators=[professionals.validators.validate_profile_photo],
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="price_per_session",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[professionals.validators.validate_price_per_session],
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="services",
            field=models.JSONField(
                default=list, validators=[professionals.validators.validate_services]
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="state",
            field=models.CharField(
                max_length=2, validators=[professionals.validators.validate_state_code]
            ),
        ),
        migrations.AlterField(
            model_name="professional",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[professionals.validators.validate_phone_number],
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="professiona_token_1b2d10_idx"),
                    models.Index(
                        fields=["user"], name="professiona_user_id_5f8fe1_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="professiona_is_veri_280e24_idx"
                    ),
                ],
            },
        ),
    ]
