# Generated by Django 4.2.7 on 2025-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "professionals",
            "0003_alter_professional_bio_alter_professional_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Cities",
                "ordering": ["state", "name"],
                "indexes": [
                    models.Index(fields=["state"], name="professiona_state_f3986f_idx"),
                    models.Index(fields=["name"], name="professiona_name_8a53a6_idx"),
                    models.Index(
                        fields=["state", "name"], name="professiona_state_ac4c31_idx"
                    ),
                ],
                "unique_together": {("state", "name")},
            },
        ),
    ]
