# Generated by Django 4.2.7 on 2025-11-07 23:30

from django.db import migrations


def populate_cities(apps, schema_editor):
    City = apps.get_model('professionals', 'City')
    
    cities_by_state = {
        'AC': ['Rio Branco', 'Cruzeiro do Sul'],
        'AL': ['Maceió', 'Arapiraca'],
        'AP': ['Macapá', 'Santana'],
        'AM': ['Manaus', 'Itacoatiara', 'Coari'],
        'BA': ['Salvador', 'Feira de Santana', 'Vitória da Conquista'],
        'CE': ['Fortaleza', 'Caucaia', 'Juazeiro do Norte'],
        'DF': ['Brasília'],
        'ES': ['Vitória', 'Vila Velha', 'Serra'],
        'GO': ['Goiânia', 'Anápolis'],
        'MA': ['São Luís', 'Imperatriz'],
        'MT': ['Cuiabá', 'Várzea Grande'],
        'MS': ['Campo Grande', 'Dourados'],
        'MG': ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora'],
        'PA': ['Belém', 'Ananindeua', 'Santarém'],
        'PB': ['João Pessoa', 'Campina Grande'],
        'PE': ['Recife', 'Jaboatão dos Guararapes', 'Olinda'],
        'PI': ['Teresina', 'Parnaíba'],
        'RJ': ['Rio de Janeiro', 'Niterói', 'Duque de Caxias', 'Nova Iguaçu'],
        'RN': ['Natal', 'Mossoró'],
        'RS': ['Porto Alegre', 'Caxias do Sul', 'Pelotas'],
        'RO': ['Porto Velho', 'Ariquemes'],
        'RR': ['Boa Vista'],
        'SC': ['Florianópolis', 'Joinville', 'Blumenau'],
        'SP': ['São Paulo', 'Guarulhos', 'Campinas', 'Santo André', 'Sorocaba', 'Ribeirão Preto', 'Santos'],
        'SE': ['Aracaju', 'Lagarto'],
        'TO': ['Palmas', 'Araguaína'],
        'PR': ['Curitiba', 'Londrina', 'Maringá'],
    }
    
    for state, cities in cities_by_state.items():
        for city_name in cities:
            City.objects.get_or_create(state=state, name=city_name)


def reverse_cities(apps, schema_editor):
    City = apps.get_model('professionals', 'City')
    City.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0005_add_password_reset_token"),
    ]

    operations = [
        migrations.RunPython(populate_cities, reverse_cities),
    ]
