# Generated by Django 4.2.7 on 2025-11-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0006_populate_brazilian_cities"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="na_contencao",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Professional has verified email and is active",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationtoken",
            name="token",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
